import { useTheme } from "@emotion/react";
import ManIcon from "@mui/icons-material/Man";
import Radio from "@mui/material/Radio";
import {
  Box,
  Button,
  FormLabel,
  MobileStepper,
  Paper,
  RadioGroup,
} from "@mui/material";
import FormControlLabel from "@mui/material/FormControlLabel";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import SwipeableViews from "react-swipeable-views";
import { autoPlay } from "react-swipeable-views-utils";

const AutoPlaySwipeableViews = autoPlay(SwipeableViews);

const Home: NextPage = () => {
  const theme = useTheme();
  const [users, setUsers] = useState<any>();
  const [activeStep, setActiveStep] = useState(0);
  const [filterValue, setFilterValue] = useState("all");
  useEffect(() => {
    axios
      .get("http://localhost:3001/users")
      .then((res) => {
        setUsers(res.data.data);
      })
      .catch((err) => console.error(err));
  }, []);

  const maxSteps = users?.length;
  const handleNext = () => {
    setActiveStep((prevActiveStep) => prevActiveStep + 1);
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1);
  };

  const handleStepChange = (step: number) => {
    setActiveStep(step);
  };

  function sexHandler(e: any) {
    setFilterValue(e.target.value);
  }
  function ageHandler(e: any) {
    setFilterValue(e.target.value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Dating App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/react/16.6.3/umd/react.production.min.js"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.6.3/umd/react-dom.production.min.js"
        />
      </Head>

      <main>
        <div
          style={{
            backgroundColor: "white",
            color: "black",
            width: "600px",
            height: "460px",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: " 10px",
          }}
        >
          <Box
            sx={{
              width: "100%",
              minHeight: "100%",
              flexGrow: 1,
            }}
          >
            <Paper
              square
              elevation={0}
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                height: 70,

                pl: 2,
                bgcolor: "background.default",
              }}
            >
              <Box component="form">
                <FormLabel
                  onChange={sexHandler}
                  id="demo-row-radio-buttons-group-label"
                >
                  Gender
                </FormLabel>
                <RadioGroup
                  row
                  aria-labelledby="demo-row-radio-buttons-group-label"
                  name="row-radio-buttons-group"
                >
                  <FormControlLabel
                    value="female"
                    control={<Radio />}
                    label="👩"
                    onChange={sexHandler}
                  />
                  <FormControlLabel
                    value="male"
                    control={<Radio />}
                    label="👨"
                    color="success"
                    onChange={sexHandler}
                  />
                  <FormControlLabel
                    value="both"
                    control={<Radio />}
                    label="👫"
                    onChange={sexHandler}
                  />
                </RadioGroup>
              </Box>
              <Box component="form">
                <FormLabel id="demo-row-radio-buttons-group-label">
                  Age
                </FormLabel>
                <RadioGroup
                  row
                  aria-labelledby="demo-row-radio-buttons-group-label"
                  name="row-radio-buttons-group"
                >
                  <FormControlLabel
                    value="a"
                    control={<Radio />}
                    label="18-25"
                    onChange={ageHandler}
                  />
                  <FormControlLabel
                    value="b"
                    control={<Radio />}
                    label="26-37"
                    onChange={ageHandler}
                  />
                  <FormControlLabel
                    value="c"
                    control={<Radio />}
                    label="37+"
                    onChange={ageHandler}
                  />
                </RadioGroup>
              </Box>
            </Paper>

            <AutoPlaySwipeableViews
              // axis={theme.direction === "rtl" ? "x-reverse" : "x"}
              index={activeStep}
              onChangeIndex={handleStepChange}
              enableMouseEvents
            >
              {users?.map((user: any, index: any) => (
                <div key={index}>
                  {Math.abs(activeStep - index) <= 2 ? (
                    <div
                      style={{
                        width: "100%",
                        minHeight: "100%",
                        display: "flex",
                        justifyContent: "space-between",
                      }}
                    >
                      <Box
                        component="img"
                        sx={{
                          maxHeight: "320px",
                          minHeight: "370px",
                          display: "flex",
                          overflow: "hidden",
                          justifyContent: "center",
                          alignItems: "center",
                        }}
                        src={user.imgURL}
                      />
                      <div
                        style={{
                          width: "50%",
                          display: "flex",
                          flexDirection: "column",
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                      >
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "space-around",
                            width: "100%  ",
                            padding: "15px",
                          }}
                        >
                          <p style={{ fontSize: "15px" }}>Name</p>
                          <p style={{ fontSize: "20px", fontWeight: "700" }}>
                            {user.firstName} {user.lastName}
                          </p>
                        </div>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "space-around",
                            width: "100%  ",
                            padding: "15px",
                          }}
                        >
                          <p style={{ fontSize: "15px" }}>Age </p>
                          <p style={{ fontSize: "20px", fontWeight: "700" }}>
                            {user.age}
                          </p>
                        </div>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "space-around",
                            width: "100%  ",
                            padding: "15px",
                          }}
                        >
                          <p style={{ fontSize: "15px" }}>Sex </p>
                          <p style={{ fontSize: "20px", fontWeight: "700" }}>
                            {user.sex}
                          </p>
                        </div>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "space-around",
                            width: "100%  ",
                            padding: "15px",
                          }}
                        >
                          <p style={{ fontSize: "15px" }}>Hobby </p>
                          <p style={{ fontSize: "20px", fontWeight: "700" }}>
                            {user.hobby}
                          </p>
                        </div>
                      </div>
                    </div>
                  ) : null}
                </div>
              ))}
            </AutoPlaySwipeableViews>
            <MobileStepper
              steps={maxSteps}
              position="static"
              activeStep={activeStep}
              nextButton={
                <Button
                  size="small"
                  onClick={handleNext}
                  disabled={activeStep === maxSteps - 1}
                >
                  Next
                </Button>
              }
              backButton={
                <Button
                  size="small"
                  onClick={handleBack}
                  disabled={activeStep === 0}
                >
                  Back
                </Button>
              }
            />
          </Box>
        </div>
      </main>
    </div>
  );
};

export default Home;
