import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import Login from "../components/Login";
import Main from "./Main";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Video Streaming App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
        skdakdsjasdjlkldjsfskj
      </main>
    </>
  );
};

export default Home;
